### PR TITLE
- Added a functionality to reset a specific campaign.

### PR DESCRIPTION
**Pull request by mjlogan**
Created an optional parameter allowing to reset only a specific campaign, if needed. Ommiting it goes to default behavior.

### CODE REVIEW

**Comment by collinkrawll** [comment]
Thanks! This has been merged and is available in the just released v1.1.0. Sorry for the delay.

**Comment by mjlogan** [comment]
Good to hear that. 
No worries!

**Comment by Belgor** [comment]
Hello mjlogan,
as you already commited a merge request do you know how to fix this issue?
https://github.com/thirdset/ThirdSetMauticResetBundle/issues
Sorry for writing here, cant find another way to contacting you.

**Comment by mjlogan** [comment]
@Belgor it doesn't seem to be something related to the plugin, please review @collinkrawll answer to your issue, it should work for you.

**Pull request merged**
